### ISSUE TITLE
VM access lost on restart

### ISSUE THREAD

**Issue by pikeas** [CenturyLinkLabs/panamax-coreos#63] opened 2014-12-18 01:04 UTC
Steps to reproduce:

    panamax reinstall
    panamax restart

Here's some log output from installation:

    panamax-vm: SSH username: core
    panamax-vm: SSH auth method: private key
    panamax-vm: Warning: Connection timeout. Retrying...
    panamax-vm:
    panamax-vm: Vagrant insecure key detected. Vagrant will automatically replace
    panamax-vm: this with a newly generated keypair for better security.
    panamax-vm:
    panamax-vm: Inserting generated public key within guest...
    panamax-vm: Removing insecure key from the guest if its present...
    panamax-vm: Key inserted! Disconnecting and reconnecting using new SSH key...

I can work around this by adding my own key to ~/core/ssh/authorized_keys and using `ssh core@panamax.local`. There's probably a better solution involving tweaking the Vagrantfile...

**Comment by nugai** [comment] 2015-01-08 09:56
I encountered the same problem (authentication fails upon `panamax restart`). I installed panamax on a Centos 7 system. Authentication and private key exchange seems to be successful during  installation and reinstallation:

`==> panamax-vm: Forwarding ports...`
`    panamax-vm: 22 => 2222 (adapter 1)`
`==> panamax-vm: Running 'pre-boot' VM customizations...`
`==> panamax-vm: Booting VM...`
`==> panamax-vm: Waiting for machine to boot. This may take a few minutes...`
`    panamax-vm: SSH address: 127.0.0.1:2222`
`    panamax-vm: SSH username: core`
`    panamax-vm: SSH auth method: private key`
`    panamax-vm: Warning: Connection timeout. Retrying...`
`    panamax-vm: `
`    panamax-vm: Vagrant insecure key detected. Vagrant will automatically replace`
`    panamax-vm: this with a newly generated keypair for better security.`
`    panamax-vm: `
`    panamax-vm: Inserting generated public key within guest...`
`    panamax-vm: Removing insecure key from the guest if its present...`
`    panamax-vm: Key inserted! Disconnecting and reconnecting using new SSH key...`
`==> panamax-vm: Machine booted and ready!`

However, when I enter `panamax restart` (or 'panamax stop' followed by `panamax up`), the console screen shows the following: 

`==> panamax-vm: Forwarding ports...`
`    panamax-vm: 22 => 2222 (adapter 1)`
`==> panamax-vm: Running 'pre-boot' VM customizations...`
`==> panamax-vm: Booting VM...`
`==> panamax-vm: Waiting for machine to boot. This may take a few minutes...`
`    panamax-vm: SSH address: 127.0.0.1:2222`
`    panamax-vm: SSH username: core`
`    panamax-vm: SSH auth method: private key`
`    panamax-vm: Warning: Connection timeout. Retrying...`
`    panamax-vm: Warning: Authentication failure. Retrying...`
`    panamax-vm: Warning: Authentication failure. Retrying...`
`    panamax-vm: Warning: Authentication failure. Retrying...`
`    panamax-vm: Warning: Authentication failure. Retrying...`
	[etc, until...]
`Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.`

`If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.`

`If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.`

`If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.`
`Starting Panamax seems to have failed. Please try again or use reinstall option.`

The VM seems to be running. I always get cAdvisor data on `http://10.0.0.200:3002/containers/`,  but sporadically I received some "api not found errors" on `http://10.0.0.200:3000/`. Other than that, I get the same results with `vagrant status` and `vagrant global-status` as `pikeas` posted above. 

The issue seems to be a Vagrant/CoreOS issue, as it is eerily similar to [this post](http://stackoverflow.com/questions/24867490/coreos-authentication-failure-on-vagrant-up) on Stackoverflow, which suggests deleting the private key. This, however, did not work for me. 
`rm -f <your_drirectory>/.panamax/machines/panamax-vm/virtualbox/private_key` followed by  `panamax restart`, Vagrant changes the insecure key and creates a new `private_key` file, but authentication still times out. Adding SSH keys (both `~/.vagrant.d/insecure_private_key` and the new `private_key` as suggested in the link also did not produce any successes.

Interestingly, the last post in the link above states "The solution of all my problem (current question and next question) was solved when I update my box of CoreOS to version 367.1.0." However, I do not have enough knowledge to investigate what version of CoreOS and/or Vagrant is used in the Panamax VM.

**Comment by nugai** [comment] 2015-01-09 21:03
FYI, CoreOS stable was updated today from VERSION=494.5.0 (used in Panamax) to VERSION=522.4.0.

**Comment by miqui** [comment] 2015-01-14 14:12
..CoreOS upgrade has no effect... still the exact same problems as described by you... my environment is ubuntu 14.04 LTS

**Comment by cakkineni** [comment] 2015-01-14 15:07
@nugai 

- Before running `vagrant status` be sure to run `panamax debug` and then run this `export VAGRANT_DOTFILE_PATH=<Path from the debug output>` .
- Also, If you're running any `vagrant` commands directly, you'll be missing some of the env vars that are used in the `Vagrantfile`. You can see those from running `panamax debug`, Its safer to use `panamax commands`.
- All that said, We're not able to replicate your issues locally yet though, we have panamax running locally on Ubuntu 14.04/12.04 without any issues. 
- Which version of vagrant are you running? Other users seemed to have some issues with 1.6.5 or later, rolling back to a previous might help.

**Comment by nugai** [comment] 2015-01-14 17:26
@cakkineni 
Thank you for your reply. 
* Using `panamax debug` and `export VAGRANT_DOTFILE_PATH=<Path from the debug output>` before `vagrant status` helped: Running this sequence of commands now gives valid results for `vagrant status` (specifically, after exporting the path,  `panamax-vm                not created (virtualbox)` changes to `panamax-vm                running (virtualbox)`.  However, exporting the path does not change the behavior of `panamax ssh`, which still fails after restart.

* I used some vagrant commands to see if I could find out if/why the `private_key` is not found (or not used or not accepted) after `panamax restart`. It would be nice if there was a `panamax status` command, as `panamax info` does not provide enough information. Also, I think it would be worthwhile to include information in `panamax debug` (or `panamax status`) about which `private_key` file panamax is using (the restart sequence clearly states `panamax-vm: SSH auth method: private key' before the `panamax-vm: Warning: Authentication failure. Retrying...` and eventually the final timeout occurs). These messages seem to come from Vagrant, but I cannot find any way to get more info from Panamax or Vagrant (foe example, I tried setting `VAGRANT_LOG=debug` before running `panamax ssh` but this gives no further or additional details than what I posted above).

* I understand and accept that you're running on Ubuntu (and I'm not) and that this may be the cause of some problems. One thing I found somewhat peculiar with the installation is that, in addition to `$VAGRANT_DOTFILE_PATH/machines/panamax-vm/virtualbox` (where the `private_key` file is located), there is also a directory structure `$VAGRANT_DOTFILE_PATH/.vagrant/machines/panamax-vm/virtualbox`, but this directory is empty (no files). In one of my debugging attempts, I copied (duplicated) the panamax files into the `.vagrant` directory structure but that made no difference. 

* As mentioned above,  I installed panamax (base box 'panamax-coreos-box-494.5.0') on a fresh Centos 7 system (kernel 3.10.0-123.13.2.el7.x86_64) with VirtualBox 4.3.20 r96996 and Vagrant 1.7.1. There is no way I will not roll back Vagrant to an earlier version.

**Comment by cakkineni** [comment] 2015-01-15 04:13
@miqui 
- Yes, the `export VAGRANT_DOT_FILE_PATH=<...>` will only help with vagrant commands. We have not yet tried the install on `CentOS 7`. We will eventually try it out and update the utility/documentation to fix any issues. 
- Also, meanwhile, since you were able to create a CentOS VM successfully, you can try to follow the cloud provider instructions (https://github.com/CenturyLinkLabs/panamax-ui/wiki/Cloud-Provider-Installation-of-Panamax-Client#amazon-web-services---ec2) and manually install `panamax` inside the VM. You'll still be able to access `panamax`, but you won't have all the cli commands, you'll have only some commands.

**Comment by nugai** [comment] 2015-01-18 10:49
@cakkineni 

I'm not sure if your message directed @miqui was actually intended for me. If so, some clarification: I'm not using a CentOS VM. CentOS 7 is my base OS running on bare metal. Inside CentOS 7, I'm running CoreOS and Panamax. I have not yet tried the cloud install, but please find below some findings on my investigation of the timeout problem. 

@Everyone

In a nutshell, it appears that `panamax restart` wipes out the SSH private_key stored inside the VM at  `/home/core/.ssh/authorized_keys` and replaced that file with Vagrant's `insecure_private_key`. Quite likely, this is either a Vagrant issue or a Panamax base box config issue (as the file gets replaced, I pretty much ruled out a CoreOS issue). So, let me first provide a quick and dirty workaround, then explain how I came to these conclusions: 

##### 1. Quick and Dirty Workaround  
Before running `panamax init` or `panamax reinstall`,  edit the file `<your_install_dir>/.panamax/Vagrantfile` and change the setting `config.ssh.insert_key = true` (default value) to `  config.ssh.insert_key = false`. This prevents the creation of a private key during init/reinstall and forces `panamax ssh` to use Vagrant's `insecure_private_key`. Obviously, the VM is no longer secure, as anybody can get the Vagrant `insecure_private_key`  -- but `panamax restart` works without problems, and so does `panamax ssh`.

##### 2. How I found and verified the problem
Note: My system is a CentOS 7 system with `su root` enabled (because I'm too lazy to type `sudo` before every shell command that requires root privileges). So, you may have to precede the commands outlined below with `sudo` if they don't work for you. Also, you will need to substitute the term <your_base_install_dir> with the actual path on your system.

###### 2.a What happens on the host system when `panamax ssh` is being used
After a plain-vanilla install, I started `panamax ssh` in one console and checked in another console on the host system with `ps aux | grep ssh` what the exact command was that Panamax issued. The result was: `ssh core@127.0.0.1 -p 2222 -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i <your_base_install_dir>/.panamax/machines/panamax-vm/virtualbox/private_key`. I could copy and paste this command in the console and have immediate SSH access to `core@panamax-vm`. 

Issuing `panamax restart` in the first console closed the session in the second console, but repeating the `ssh core@127.0.0.1 -p 2222 .../private_key` command did not log me into the VM and only produced a login prompt. While the first console showed the `panamax-vm: Warning: Authentication failure. Retrying...` messages (and also after the connection times out), the only way to access the VM at console level was by using `ssh core@127.0.0.1 -p 2222 -o Compression=yes -o DSAAuthentication=yes -o LogLevel=FATAL -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -i <your_base_install_dir>/.vagrant.d/insecure_private_key`. 

###### 2.b What happens on the `panamax-vm` before and after `panamax restart`
Each time `panamax init` or `panamax restart` is run on the host system, Vagrant creates a private SSH key, which is stored inside the Panamax VM in the file `/home/core/.ssh/authorized_keys`. Hence, when using `panamax ssh` (or the direct SSH commands described above), the key can be checked using the command `cat /home/core/.ssh/authorized_keys`. 

Directly after  `panamax init` or `panamax restart`, the command  `cat /home/core/.ssh/authorized_keys` shows something like: 

`# auto-generated by /usr/bin/update-ssh-keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1iVH/uqCLXyC/uORDa2Qx3zFMSFZmzLfDonztHISKuyLIWRuU1EenSXgF/mcfBKyc6rRwsh6wxAcjRP2CWev7lsO6c0z9tKJqIi5BNPAaweonaDYOSILMofER6DzzUojK3QS6T0ftZoN0/MITwkVDsgcrM2nZT3RXCnpIZ/3+CQEWqb3Uuv6aLNKVQBgIb1ZSpGorhNKukSshRGDly/miDeQIJmujokmrzzdJ9NgEjCvKGzymXk6/nCIo7h8ETDqy1elUKp8/yBjK2FFYJxOrhAt7N7N4pWltQ0R0oiQTaCFyr3IqkT4A1pjsR/hlbuujURtkvfNSIqw4aLLZawUH vagrant`

Note the comment "vagrant" at the end of the file.

When the VM has been restarted using `panamax restart`, the file `/home/core/.ssh/authorized_keys` has been changed. The command  `core@panamax-vm ~ $ cat .ssh/authorized_keys` now shows:

`# auto-generated by /usr/bin/update-ssh-keys
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key`

Now note the comment "vagrant insecure public key" at the end of the file. 
Also, `ls -l /home/core/.ssh/authorized_keys` shows different time stamps.

##### 3. Conclusions
I am 100% certain that `panamax restart` overwrites the private SSH key generated during init or reinstall.

As mentioned above, I believe this is either a Vagrant issue or a Panamax base box config issue. 

I tried to modify the files on the VM, but the file system is mounted read-only and therefore no changes are possible -- hence, the simplest work-around (that also guarantees all Panamax background processes work as intended) is to use the insecure private key until another solution is found.

**Comment by pikeas** [comment] 2015-01-29 22:32
This appears to be resolved by Panamax 0.3.5, which uses Vagrant's insecure key.

**Comment by rossjimenez** [comment] 2015-01-29 22:36
Resolved by Panamax installer build v 0.3.5

**Closed by rossjimenez** 2015-01-29 22:36 UTC
